### ISSUE TITLE
Instruction to use the repo

### ISSUE THREAD

**Issue by raypretam** [synlp/DMPar#1]
Thanks for the great work. I am impressed to get to know people who have already worked on such a problem of incorporating dependency into an encoder-based model. Please provide instructions on how to run the repo. And I am not able to find run.sh file anywhere in the repo. Am I missing something? 

Thanks and Regards.

**Comment by yuanheTian** [comment]
Thanks for being interested in our work. The bash files are uploaded. Please check

**Comment by raypretam** [comment]
Thanks, but I figured it out from the dep_main.py file.
